<?php
$title = 'Update Images';
$description = 'In this section you can import product images loading a .XLSX or .CSV file';
$linkToTutorial = '';

?>
<script type="text/javascript">
    function resizeIframe(obj) {
        obj.style.height = obj.contentWindow.document.documentElement.scrollHeight + 'px';
    }
    const startUrl = '<?php echo Mage::getUrl('mediaio/adminhtml_media_update/update'); ?>'
    const validateUrl = '<?php echo Mage::getUrl('mediaio/adminhtml_import/validateFile'); ?>'
    const batchesUrl = '<?php echo Mage::getUrl('mediaio/adminhtml_import/batches'); ?>'
    const templatesUrl = '<?php echo Mage::getUrl('mediaio/adminhtml_templates/set'); ?>'
    const loaderGifUrl = '<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>'
    const formKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>'
    const templatePath = '<?php echo TEMPLATES_PRODUCTS_UPDATE; ?>'
    var row = 2
    loadTemplates()
</script>
<?php
include(__DIR__ . '/../components/contentHeader.phtml');
include(__DIR__ . '/../components/mainContainer.phtml');
?>
<label for='file' class='description-text'>Select your file:</label>
<input type='file' name='file' id='file'>
<div class='templates-section'>
    <select name='template' id='template'></select>
</div>
<br>
<hr>
<br>
<button class='scalable' id='import'><?php echo $title; ?></button>
<br>
<div id='logs'>
    <div id='log-div'>
        <div style='width: 97%;' id='details'></div>
        <div style='width: 3%;' id='loader'></div>
    </div>
    <div id='progress'></div>
</div>
<iframe id='loadarea' style='display:none;'></iframe><br>
</div>
</div>
</fieldset>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<style type="text/css">
    #idIframe {
        width: 100%;
        border: none;
    }

    #idIframe2 {
        width: 100%;
        border: none;
    }

    .help-modal {
        margin-top: 10px;
    }

    .help-modal .help-modal-message {
        padding: 10px 15px;
        background-color: #fff;
        border-radius: 5px;
        border: 1px solid #eee;
        font-size: 13px;
    }

    #import,
    #export {
        display: block !important;
    }

    .help-modal .help-modal-message i {
        color: #3580c3;
        margin-right: 10px;
    }

    .help-modal .help-modal-message:hover {
        color: #00b7ff
    }

    body {
        background-color: transparent;
    }

    input[type="date"]::-webkit-inner-spin-button,
    input[type="date"]::-webkit-calendar-picker-indicator {
        display: none;
        -webkit-appearance: none;
    }

    .templates-section {
        min-width: 200px;
        width: fit-content;
        margin-top: 10px;
        background: transparent;
        vertical-align: middle;
        display: flex;
        flex-direction: column;
    }

    .table-title {
        color: #ffffff;
        font-weight: 300;
        font-size: 14px;
    }

    .attr-table {
        width: fit-content;
        background: #f2f2f2;
    }

    .products-attr {
        color: #888888;
        padding: 10px;
        font-size: 13px;
        text-align: center;
        font-family: 'Roboto';
    }

    #logs {
        display: none;
        height: 200px;
        flex-direction: column;
        width: 50%;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-top: 20px;
        padding: 1%;
    }

    #log-div {
        height: 75%;
        border: 1px solid #ccc;
        padding: 1% 2%;
        display: flex;
        overflow-y: scroll;
    }

    #progress {
        height: 20%;
        display: flex;
        padding-left: 2%;
        margin-top: 2%;
        align-items: center;
        background: #ccc;
    }

    #progress>p {
        margin: 0;
    }
</style>