<div class="content-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-9">
                <h3 class="icon-head head-tax"><?php echo $title;?></h3>
                <ul class="breadcrumb">
                    <li>
                        Dashboard
                    </li>
                    <li>
                        <span><?php echo $title;?></span>
                    </li>
                </ul>
            </div>
            <div class="col-sm-6 col-xs-3 form-buttons"></div>
        </div>
    </div>
</div>